[package]
name = "dhd"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
serialport = "4.3"
serde_json = "1.0"
anyhow = "1.0"
colored = "2.1"
chrono = "0.4"
libpulse-binding = "2.28"
ksni = "0.3"
daemonize = "0.5"
fs2 = "0.4"
tokio = { version = "1.0", features = ["full"] }
tokio-serial = "5.4"
tokio-util = { version = "0.7", features = ["codec"] }
futures = "0.3"
clap = { version = "4.5", features = ["derive", "env"] }
